DROP TABLE IF EXISTS Passager CASCADE;
DROP TABLE IF EXISTS Pilote CASCADE;
DROP TABLE IF EXISTS Technique CASCADE;
DROP TABLE IF EXISTS Stewart CASCADE;
DROP TABLE IF EXISTS HoteAccueil CASCADE;
DROP TABLE IF EXISTS Porte CASCADE;
DROP TABLE IF EXISTS Terminal CASCADE;
DROP TABLE IF EXISTS Personne CASCADE;
